### ISSUE TITLE
Erro generating page: build_html/index.html

### ISSUE THREAD

**Issue by brandon-bethke-timu** [appbaseio/DocBase#15]
When I perform the following steps I get an error in the console and a blank page is displayed when I hit the local site. Can't figure out if this is an issue with the product or not.

*) yo docbase
*) <enter> when prompted
*) For hosted option select 'Magic'
*) For publish option select 'Locally'
*) For color option select 'green'

...stuff is printed to console

Running "docbase:def" (docbase) task
starting 
Erro generating page: build_html/index.html

**Comment by siddharthlatest** [comment]
We have seen a related issue when phantomjs starts converting SPA routes to an html site, [link to known issue](http://appbaseio.github.io/docbase-manual/v1/getting-started/installation-issues.html#installation-issues-running-yo-docbase).

The tl;dr recommendation is to delete the **build_html/** directory, and run grunt (which starts the docbase:def task). If the build succeeds, the generator should start an http-server after the grunt execution. Or if you prefer to run it manually, the html site will be created under the **build_html/** directory.

**Comment by brandon-bethke-timu** [comment]
Sorry, it's not working. I installed phantomjs using npm, version 2.1.1 was installed. I still get the error. The **build_html/** directory never is created / doesn't exist.

**Comment by siddharthlatest** [comment]
Can you share the log output from `yo docbase`? It's hard to tell without
it.

On Wed, Apr 6, 2016 at 1:03 AM, brandon-bethke-neudesic <
notifications@github.com> wrote:

> Sorry, it's not working. I installed phantomjs using npm, version 2.1.1
> was installed. I still get the error. The _build_html/_ directory never
> is created / doesn't exist.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/appbaseio/Docbase/issues/15#issuecomment-205960327

ᐧ
ᐧ

**Comment by brandon-bethke-timu** [comment]
[TerminalOutput.txt](https://github.com/appbaseio/Docbase/files/205439/TerminalOutput.txt)

**Comment by siddharthlatest** [comment]
@brandon-bethke-neudesic this tells us that your installation is going well, but there is a failure in the html pages creation task in the grunt process. It does not tell us the nature of failure.

@mateusfreira introduced a new commit in the grunt process that should provide debug information on failure. You can now set the parameter **enableCrawlerDebug** in './node_modules/grunt-docbase/tasks/docbase.js#L34' to true and docbase will print the necessary debug information for us to fix this.

**Comment by brandon-bethke-timu** [comment]
Thank you. Here is the terminal output with the **enableCrawlerDebug** flag set.

[TerminalOutput2.txt](https://github.com/appbaseio/Docbase/files/206714/TerminalOutput2.txt)

**Comment by siddharthlatest** [comment]
@brandon-bethke-neudesic are you using Docbase as a root user? Able to replicate the bug in that scenario.

**Comment by brandon-bethke-timu** [comment]
I am using a mac and I am logged as an Admin user, but I am not doing a sudo or anything like that.

**Comment by siddharthlatest** [comment]
What is the output of `ls -l` after the build failure error?

**Comment by brandon-bethke-timu** [comment]
[lsoutput.txt](https://github.com/appbaseio/Docbase/files/208858/lsoutput.txt)

**Comment by siddharthlatest** [comment]
@brandon-bethke-neudesic thanks, it's missing the **bower_components/** directory. That's the reason document generation is failing, working on a fix.

**Comment by siddharthlatest** [comment]
@brandon-bethke-neudesic a new yeoman generator has been released that addresses this. Does it work for you?

**Comment by brandon-bethke-timu** [comment]
I am sorry, but it does not work. I uninstalled and then re-installed yo and docbase-generator. I get the same error message and the **bower_components/** directory is not there.

**Comment by mateusfreira** [comment]
@brandon-bethke-neudesic can you execute manually the command 

``` bash
bower install --allow-root
```

and send us the result?

**Comment by brandon-bethke-timu** [comment]
Is **bower** something that needs to be installed manually? because it's not in the **node_modules** folder and I get **command not found** when I try to execute the command.

**Comment by siddharthlatest** [comment]
@brandon-bethke-neudesic yes, it can be installed with `npm install -g bower`. Docbase currently assumes `npm`, `bower` and `grunt-cli` to be installed on the user's system.

**Comment by brandon-bethke-timu** [comment]
In conclusion, the problem appears to have been that **bower** was not installed. Sorry.

**Comment by clarkd** [comment]
I'm seeing this issue but have bower, npm, grunt-cli installed etc. We're running on Ubuntu. Any ideas what else to check?

**Comment by siddharthlatest** [comment]
@clarkd Can you set the parameter enableCrawlerDebug in './node_modules/grunt-docbase/tasks/docbase.js#L34' to true and share the resulting output?

**Comment by clarkd** [comment]
@siddharthlatest I've managed to get it working by installing a previous version of Phantom. All going well now! Pretty happy with the docs already although a quick question - does it support multi-level nav beyond a single dropdown/depth?

**Comment by siddharthlatest** [comment]
@clarkd It doesn't support that right now.
