### ISSUE TITLE
Sidebar highlight doesn't work for html mode.

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/DocBase#7]
The code snippet below is responsible for showing the active section in the sidebar during a doc navigation. It's present in the SPA mode, but when grunt converts the page to html mode. We need to execute the following script on each page for highlighting to work:

```
var $window = $(window);
    var $document = $(document);
    $document.on('ready', function() {
      $("h2, h3").scrollagent(function(cid, pid, currentElement, previousElement) {
        if (pid) {
         $("[pref='#"+pid+"']").removeClass('active');
        }
        if (cid) {
          $("[pref='#"+cid+"']").addClass('active');
        }
      });
    });
```

It's originally present in the flatdoc's theme file, but we miss adding the JS while converting to html mode - https://github.com/appbaseio/Docs/blob/master/bower_components/flatdoc/theme-white/script.js#L9

**Comment by mateusfreira** [comment]
Released in https://github.com/appbaseio/Docbase/releases/tag/0.1.3
